version: '3'

services:
  sensor01:
    build: .
    command: python3 -u sw_sensor.py sensor_01 1 5000
  sensor02:
    build: .
    command: python3 -u sw_sensor.py sensor_02 1 35
  sensor03:
    build: .
    command: python3 -u sw_sensor.py sensor_03 1 120
  sensor04:
    build: .
    command: python3 -u sw_sensor.py sensor_04 1 6500
  eventfilter:
    build: .
    command: python3 -u event_filter.py
  dashboard:
    build: .
    command: bokeh serve dashboard
    ports:
      - "5006:5006"